In [1]:
import pandas as pd
import numpy as np

In [5]:
data_file = {
    'riders': ('signup_date',),
    'sessions': ('session_time',),
    'trips': ('pickup_time', 'dropoff_time'),
    'promotions': ('start_date', 'end_date'),
    'drivers': ('signup_date','last_active')

}
dfs = {}
for name, date_cols in data_file.items():
    dfs[name] = pd.read_csv(f'../data/{name}.csv', parse_dates=list(date_cols))

In [6]:
dfs['riders']

,user_id,signup_date,loyalty_status,age,city,avg_rating_given,churn_prob,referred_by
0,R00000,2025-01-24,Bronze,34.729629,Nairobi,5.0,0.142431,R00001
1,R00001,2024-09-09,Bronze,34.571020,Nairobi,4.7,0.674161,NaN
2,R00002,2024-09-07,Bronze,47.133960,Lagos,4.2,0.510379,NaN
3,R00003,2025-03-17,Bronze,41.658628,Nairobi,4.9,0.244779,NaN
4,R00004,2024-08-20,Silver,40.681709,Lagos,3.9,0.269960,R00002
...,...,...,...,...,...,...,...,...
9995,R09995,2025-04-26,Silver,20.688176,Lagos,4.4,0.028371,NaN
9996,R09996,2023-07-26,Silver,18.000000,Cairo,4.1,0.290365,NaN
9997,R09997,2025-04-18,Bronze,34.197784,Lagos,4.7,0.013147,R02155
9998,R09998,2024-01-10,Bronze,51.705319,Cairo,3.8,0.253959,R07447
9999,R09999,2025-03-29,Gold,36.089597,Nairobi,3.9,0.401529,NaN

In [9]:
dfs['drivers']

,driver_id,rating,vehicle_type,signup_date,last_active,city,acceptance_rate
0,D00000,3.1,SUV,2025-01-20,2025-01-06 18:23:09.312275,Cairo,0.679555
1,D00001,5.0,Sedan,2023-03-27,2025-04-27 01:44:02.472554,Nairobi,0.548786
2,D00002,4.5,Motorcycle,2024-05-02,2025-03-07 19:24:46.367672,Nairobi,0.593724
3,D00003,5.0,Motorcycle,2023-04-16,2025-03-26 19:16:24.253793,Nairobi,0.990000
4,D00004,4.4,Motorcycle,2023-05-28,2025-04-08 18:54:44.649615,Lagos,0.519773
...,...,...,...,...,...,...,...
4995,D04995,4.7,Sedan,2022-06-22,2025-04-22 06:53:04.106359,Lagos,0.694777
4996,D04996,3.5,Sedan,2024-12-29,2025-01-13 15:31:06.435774,Lagos,0.749438
4997,D04997,4.1,SUV,2024-01-21,2025-04-16 08:52:20.862471,Cairo,0.827244
4998,D04998,4.2,Sedan,2024-08-14,2025-04-06 03:43:04.711508,Cairo,0.520124
4999,D04999,4.1,Sedan,2023-05-03,2025-02-09 05:47:23.165252,Cairo,0.685382

In [8]:
dfs['promotions']

,promo_id,promo_name,promo_type,promo_value,start_date,end_date,target_segment,city_scope,ab_test_groups,test_allocation,success_metric
0,P000,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-25,All,Nairobi,['All'],[1.0],Usage Frequency
1,P001,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-22,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
2,P002,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-16,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
3,P003,Loyalty Bonus,points,100.0,2025-04-26,2025-05-04,Gold+,Nairobi,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
4,P004,Loyalty Bonus,points,100.0,2025-04-26,2025-05-15,Gold+,Nairobi,['All'],[1.0],Usage Frequency
5,P005,Loyalty Bonus,points,100.0,2025-04-26,2025-05-16,Gold+,Nairobi,['All'],[1.0],Usage Frequency
6,P006,First Ride Discount,discount,0.3,2025-04-26,2025-05-06,New,Lagos,['All'],[1.0],Usage Frequency
7,P007,First Ride Discount,discount,0.3,2025-04-26,2025-05-26,New,Nairobi,['All'],[1.0],ROI
8,P008,Referral Special,credit,15.0,2025-04-26,2025-05-03,Active,All-Cities,['All'],[1.0],Usage Frequency
9,P009,Referral Special,credit,15.0,2025-04-26,2025-05-18,Active,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
10,P010,First Ride Discount,discount,0.3,2025-04-26,2025-05-05,New,All-Cities,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
11,P011,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-24,All,Nairobi,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
12,P012,Loyalty Bonus,points,100.0,2025-04-26,2025-05-09,Gold+,All-Cities,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
13,P013,First Ride Discount,discount,0.3,2025-04-26,2025-05-09,New,All-Cities,['All'],[1.0],ROI
14,P014,First Ride Discount,discount,0.3,2025-04-26,2025-05-19,New,Lagos,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
15,P015,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-17,All,All-Cities,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
16,P016,Loyalty Bonus,points,100.0,2025-04-26,2025-05-06,Gold+,Lagos,['All'],[1.0],Usage Frequency
17,P017,First Ride Discount,discount,0.3,2025-04-26,2025-05-06,New,Lagos,['All'],[1.0],ROI
18,P018,First Ride Discount,discount,0.3,2025-04-26,2025-05-13,New,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
19,P019,First Ride Discount,discount,0.3,2025-04-26,2025-05-08,New,Lagos,['All'],[1.0],Conversion Rate

In [11]:
dfs['sessions']

,session_id,rider_id,session_time,time_on_app,pages_visited,converted,city,loyalty_status
0,S000000,R08605,2025-04-27 18:57:06+02:05,79,4,1,Cairo,Bronze
1,S000001,R08823,2025-04-27 07:32:22+02:27,101,3,0,Nairobi,Silver
2,S000002,R05342,2025-04-27 23:17:25+02:05,12,1,0,Cairo,Bronze
3,S000003,R05057,2025-04-27 14:40:25+00:14,19,1,0,Lagos,Silver
4,S000004,R09614,2025-04-27 08:31:22+00:14,4,1,0,Lagos,Bronze
...,...,...,...,...,...,...,...,...
49995,S049995,R03092,2025-04-27 07:52:18+00:14,76,5,0,Lagos,Bronze
49996,S049996,R02272,2025-04-27 16:52:12+02:05,44,1,1,Cairo,Bronze
49997,S049997,R06892,2025-04-27 14:02:26+02:27,9,5,0,Nairobi,Bronze
49998,S049998,R03121,2025-04-27 03:45:34+00:14,65,2,0,Lagos,Bronze
49999,S049999,R06505,2025-04-27 17:18:42+02:27,32,1,0,Nairobi,Bronze

In [12]:
dfs['trips']

,trip_id,user_id,driver_id,fare,surge_multiplier,tip,payment_type,pickup_time,dropoff_time,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng,weather,city,loyalty_status
0,T000000,R05207,D00315,12.11,1.0,0.00,Card,2024-11-27 18:41:50+02:27,2024-11-27 19:33:50+02:27,-1.108123,36.912209,-1.068155,36.875377,Foggy,Nairobi,Bronze
1,T000001,R09453,D03717,8.73,1.0,0.02,Card,2024-10-28 23:13:48+00:14,2024-10-28 23:26:48+00:14,6.675266,3.515740,6.641734,3.525620,Sunny,Lagos,Gold
2,T000002,R00567,D02035,19.68,1.0,0.00,Card,2025-02-17 05:36:41+02:27,2025-02-17 05:52:41+02:27,-1.248589,37.010668,-1.273182,37.018586,Cloudy,Nairobi,Bronze
3,T000003,R09573,D02657,16.43,1.0,0.01,Mobile Money,2024-06-18 19:27:14+02:05,2024-06-18 19:32:14+02:05,29.819554,31.188780,29.837689,31.232978,Cloudy,Cairo,Bronze
4,T000004,R03446,D01026,8.70,1.0,1.06,Card,2024-10-05 09:58:16+02:27,2024-10-05 10:28:16+02:27,-1.676479,36.729219,-1.638395,36.694063,Sunny,Nairobi,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,T199995,R08022,D04562,26.79,1.3,0.00,Card,2025-03-14 18:16:26+00:14,2025-03-14 18:27:26+00:14,6.511389,3.297189,6.545565,3.327685,Cloudy,Lagos,Silver
199996,T199996,R05421,D03984,14.65,1.0,0.00,Card,2024-07-02 06:59:36+00:14,2024-07-02 07:36:36+00:14,6.489143,3.492786,6.453581,3.514289,Sunny,Lagos,Bronze
199997,T199997,R06619,D01173,12.87,1.2,0.00,Mobile Money,2024-05-06 20:38:57+00:14,2024-05-06 21:25:57+00:14,6.459348,3.527623,6.451930,3.521616,Rainy,Lagos,Bronze
199998,T199998,R02867,D00974,17.18,1.3,0.00,Mobile Money,2024-09-25 03:11:33+00:14,2024-09-25 03:45:33+00:14,6.540074,3.471683,6.540339,3.426481,Rainy,Lagos,Gold
199999,T199999,R07749,D04894,13.47,1.0,0.00,Card,2024-05-24 18:19:39+02:05,2024-05-24 18:51:39+02:05,30.234277,30.884004,30.279227,30.874865,Sunny,Cairo,Bronze

In [17]:
#checking data quality of the dataframes

def data_quality_check(df, name):
    print(f"{name.upper()}")
    print(f"{'-' * 60}")

    print(f"Duplicate Rows: {df.duplicated().sum()}")
    print(f"\nNull counts: )")
    
    print(df.isnull().sum())
    print(df.dtypes)
    print()

data = { 'sessions', 'trips', 'promotions', 'drivers', 'riders'}
for name in data:
    data_quality_check(dfs[name], name)

PROMOTIONS
------------------------------------------------------------
Duplicate Rows: 0

Null counts: )
promo_id           0
promo_name         0
promo_type         0
promo_value        0
start_date         0
end_date           0
target_segment     0
city_scope         0
ab_test_groups     0
test_allocation    0
success_metric     0
dtype: int64
promo_id                      str
promo_name                    str
promo_type                    str
promo_value               float64
start_date         datetime64[us]
end_date           datetime64[us]
target_segment                str
city_scope                    str
ab_test_groups                str
test_allocation               str
success_metric                str
dtype: object

DRIVERS
------------------------------------------------------------
Duplicate Rows: 0

Null counts: )
driver_id          0
rating             0
vehicle_type       0
signup_date        0
last_active        0
city               0
acceptance_rate    0
dtype: int64
driver_id                     str
rating                    float64
vehicle_type                  str
signup_date        datetime64[us]
last_active        datetime64[us]
city                          str
acceptance_rate           float64
dtype: object

RIDERS
------------------------------------------------------------
Duplicate Rows: 0

Null counts: )
user_id                0
signup_date            0
loyalty_status         0
age                    0
city                   0
avg_rating_given       0
churn_prob             0
referred_by         6947
dtype: int64
user_id                        str
signup_date         datetime64[us]
loyalty_status                 str
age                        float64
city                           str
avg_rating_given           float64
churn_prob                 float64
referred_by                    str
dtype: object

SESSIONS
------------------------------------------------------------
Duplicate Rows: 0

Null counts: )
session_id        0
rider_id          0
session_time      0
time_on_app       0
pages_visited     0
converted         0
city              0
loyalty_status    0
dtype: int64
session_id          str
rider_id            str
session_time        str
time_on_app       int64
pages_visited     int64
converted         int64
city                str
loyalty_status      str
dtype: object

TRIPS
------------------------------------------------------------
Duplicate Rows: 0

Null counts: )
trip_id             0
user_id             0
driver_id           0
fare                0
surge_multiplier    0
tip                 0
payment_type        0
pickup_time         0
dropoff_time        0
pickup_lat          0
pickup_lng          0
dropoff_lat         0
dropoff_lng         0
weather             0
city                0
loyalty_status      0
dtype: int64
trip_id                 str
user_id                 str
driver_id               str
fare                float64
surge_multiplier    float64
tip                 float64
payment_type            str
pickup_time             str
dropoff_time            str
pickup_lat          float64
pickup_lng          float64
dropoff_lat         float64
dropoff_lng         float64
weather                 str
city                    str
loyalty_status          str
dtype: object